### ISSUE TITLE
Thoughts on custom <select> elements using just CSS?

### ISSUE THREAD

**Issue by jonscottclark** [filamentgroup/select#3]
In Bootstrap v4, they simply use CSS to style a select box. http://v4-alpha.getbootstrap.com/components/forms/#select-menu

It seems like the **appearance** property is helping to style this from the ground up. Thoughts on whether this is preferable or whether this has too many limitations?

Here's the CSS:

``` css
    display: inline-block;
    max-width: 100%;
    -webkit-appearance: none;
    padding: .375rem 1.75rem .375rem .75rem;
    padding-right: .75rem\9;
    color: #55595c;
    vertical-align: middle;
    background: #fff url(data:image/png;base64, ...) no-repeat right .75rem center;
    background-image: none\9;
    -webkit-background-size: 8px 10px;
    background-size: 8px 10px;
    border: 1px solid #ccc;
    -moz-appearance: none;
```

**Comment by toddparker** [comment]
@jonscottclark - Good question. We have been tinkering with a pure CSS styles select that uses the appearance property like you mentioned. That is maintained in this repo:
https://github.com/filamentgroup/select-css

I think what we're doing is close to Boostrap's approach but we've worked around a few more quirks from what I can see in code above.
